import { Link } from "react-router-dom";

export default function GstReconciliation30Minutes() {
  return (
    <div className="blog-content">

      {/* ── PROBLEM ── */}
      <div className="section-label">
        <span className="pill pill-problem">The Problem</span>
        <hr />
      </div>

      <h2>The GST Filing Firefight That Repeats Every Single Month</h2>

      <p>
        Ask any CA partner what the last week of the month looks like and you will hear the same
        story. The associate opens Outlook to chase clients for purchase invoices. Someone downloads
        GSTR-2B and starts comparing it to the purchase register in Excel. ITC mismatches pile up.
        Vendors haven't uploaded. The 3B deadline is tomorrow. The partner signs off at 11pm.
      </p>

      <p>Next month, the exact same thing happens. Different client. Same firefight.</p>

      <div className="time-compare">
        <div className="tc-side tc-old">
          <span className="tc-label">Manual Process</span>
          <span className="tc-time">2–3 Days</span>
          <span className="tc-desc">GSTR-1, 2B matching, ITC reconciliation, 3B computation — all manual, all Excel</span>
        </div>
        <div className="tc-mid">
          <span>→</span>
          <small>vs</small>
        </div>
        <div className="tc-side tc-new">
          <span className="tc-label">With Lekha AI</span>
          <span className="tc-time">30 Min</span>
          <span className="tc-desc">~80% automated, exceptions flagged with reasoning, CA reviews and approves</span>
        </div>
      </div>

      <h3>Why GST Compliance Is So Painful Every Month</h3>
      <p>
        The problem is not that your team is slow. The problem is that the monthly GST cycle has ten
        steps, five different systems, and three points where human judgment is genuinely required —
        buried inside two days of mechanical work that should never have needed a human in the first
        place.
      </p>

      <ul className="chaos-list">
        <li>
          <span className="icon">📂</span>
          <span>Sales and purchase data arrives in different formats from different clients — ERP exports, Tally data, Excel sheets, PDFs — and none of it is ready to reconcile without first being normalised.</span>
        </li>
        <li>
          <span className="icon">🔗</span>
          <span>GSTR-2B and the purchase register are generated by entirely different systems and never match on the first pass. Someone always has to sit in between.</span>
        </li>
        <li>
          <span className="icon">⚖️</span>
          <span>ITC reconciliation requires real judgment — eligible vs. ineligible, RCM entries, blocked credits, vendor-chase decisions — and it is also the most time-consuming step by far.</span>
        </li>
        <li>
          <span className="icon">⏰</span>
          <span>The 11th and 20th don't move. So the team compresses everything into the last few days — and makes errors under deadline pressure that show up as notices three months later.</span>
        </li>
        <li>
          <span className="icon">💸</span>
          <span>A wrong ITC claim is not just a software error. It is denied credit, interest liability, and a notice from the department — with real financial consequences for your client.</span>
        </li>
      </ul>

      <div className="callout">
        <p>
          <strong>The real cost:</strong> It is not just the 2–3 days per client. For a firm handling
          20 clients, that is <strong>40–60 person-days of mechanical work every single month</strong>{" "}
          — work that could be automated — leaving almost no time for the advisory and judgment-based
          work that actually builds a firm's value.
        </p>
      </div>

      {/* ── THE WORKFLOW ── */}
      <div className="section-label">
        <span className="pill pill-solution">The Monthly Workflow</span>
        <hr />
      </div>

      <h2>The 10-Step GST Cycle — and Where It Actually Breaks</h2>

      <p>
        Here is what the monthly GST compliance cycle looks like for one client — every step, every
        system, every friction point. The step marked in red is where most of the time goes and most
        of the risk lives.
      </p>

      <table className="workflow-table">
        <thead>
          <tr>
            <th>#</th>
            <th>Step</th>
            <th>System</th>
            <th>Friction</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td className="step-num-cell">1</td>
            <td>Chase &amp; collect client data — sales, purchase, invoices</td>
            <td>Outlook + WhatsApp + ERP/Tally</td>
            <td className="friction-cell">Formats vary; data always late</td>
          </tr>
          <tr>
            <td className="step-num-cell">2</td>
            <td>Normalise &amp; validate outward supplies</td>
            <td>Excel / GST software</td>
            <td className="friction-cell">HSN/rate cleanup; e-invoice/IRN matching</td>
          </tr>
          <tr>
            <td className="step-num-cell">3</td>
            <td>File GSTR-1 / IFF by 11th</td>
            <td>GST portal</td>
            <td className="friction-cell">Sequential dependency on prior data</td>
          </tr>
          <tr>
            <td className="step-num-cell">4</td>
            <td>Download GSTR-2B + take IMS actions</td>
            <td>GST portal</td>
            <td className="friction-cell">Vendor non-upload; deemed-accept risk</td>
          </tr>
          <tr className="hard-step">
            <td className="step-num-cell">5</td>
            <td><strong>ITC reconciliation</strong> — books vs. 2B + categorise (eligible / ineligible / RCM / s.17(5) blocked)</td>
            <td>Associate + SME for judgement</td>
            <td className="friction-cell">⚠️ The hardest, most judgement-laden, most time-burning step</td>
          </tr>
          <tr>
            <td className="step-num-cell">6</td>
            <td>Compute 3B liability — output ITC + RCM + interest</td>
            <td>Portal / Excel</td>
            <td className="friction-cell">Non-editable auto-pop; tie-outs</td>
          </tr>
          <tr>
            <td className="step-num-cell">7</td>
            <td>Client/partner sign-off on tax payable</td>
            <td>Outlook / in-person</td>
            <td className="friction-cell">Approval latency at deadline</td>
          </tr>
          <tr>
            <td className="step-num-cell">8</td>
            <td>Pay + file GSTR-3B by 20th</td>
            <td>GST portal</td>
            <td className="friction-cell">Deadline crunch across many clients at once</td>
          </tr>
          <tr>
            <td className="step-num-cell">9</td>
            <td>Handle routine notices / queries</td>
            <td>Portal / Outlook</td>
            <td className="friction-cell">Context-switching mid-cycle</td>
          </tr>
          <tr>
            <td className="step-num-cell">10</td>
            <td>File working papers, update tracker</td>
            <td>OneDrive / local Excel / human memory</td>
            <td className="friction-cell">Knowledge trapped in files &amp; heads</td>
          </tr>
        </tbody>
      </table>

      <div className="callout">
        <p>
          <strong>Step 5 is the bottleneck:</strong> ITC reconciliation is the hardest, most
          judgment-laden, most time-burning step in the entire cycle. It is also{" "}
          <strong>the step where a wrong call has the most serious consequences</strong> — denied
          ITC, interest, notices. And it is currently done manually, under deadline pressure, for
          every client, every month.
        </p>
      </div>

      <h3>The Six GST Errors That Hide in Every Manual Reconciliation</h3>

      <div className="error-grid">
        <div className="error-card">
          <span className="etag">Error Type 1</span>
          <p><strong>ITC claimed not in GSTR-2B</strong> — Credit taken in books but vendor hasn't uploaded the invoice. Department auto-reverses it with interest. Client gets a notice.</p>
        </div>
        <div className="error-card">
          <span className="etag">Error Type 2</span>
          <p><strong>Ineligible ITC claimed</strong> — Credit on blocked items (Section 17(5)) or personal-use expenses incorrectly claimed as business. Penalty and reversal risk.</p>
        </div>
        <div className="error-card">
          <span className="etag">Error Type 3</span>
          <p><strong>RCM liability not accounted</strong> — Reverse Charge Mechanism applies but wasn't identified. Tax liability underpaid. Interest from the date of supply.</p>
        </div>
        <div className="error-card">
          <span className="etag">Error Type 4</span>
          <p><strong>Period mismatch on ITC</strong> — Invoice received in March, GSTR-2B reflects it in April. ITC taken in wrong period. Creates reconciliation tails that chase every future month.</p>
        </div>
        <div className="error-card">
          <span className="etag">Error Type 5</span>
          <p><strong>Vendor not chased — deemed accept</strong> — IMS action deadline missed. System auto-accepts or auto-rejects. Credit position changes without the CA knowing.</p>
        </div>
        <div className="error-card">
          <span className="etag">Error Type 6</span>
          <p><strong>GSTR-1 vs. 3B mismatch</strong> — Output liability in 3B doesn't match what was filed in GSTR-1. Creates scrutiny, notices, and reconciliation work across both returns.</p>
        </div>
      </div>

      <p>
        A manual process catches some of these. A well-built AI GST reconciliation engine catches all
        of them — with explanations, source references, and a human review step before anything is
        filed.
      </p>

      <div className="pull-quote">
        <p>A wrong GST filing is not a software bug. It is denied ITC, interest, a notice, and a client's trust.</p>
      </div>

      {/* ── SOLUTION ── */}
      <div className="section-label">
        <span className="pill pill-solution">The Solution</span>
        <hr />
      </div>

      <h2>How Lekha AI Handles GST Reconciliation — Without Touching a Single Live Filing</h2>

      <p>
        Every AI vendor promises savings. But the honest question for a CA firm is not "do you
        believe the demo?" It is: "how do you get the upside with none of the downside?" Lekha AI's
        answer is the parallel run — and it is the only way we ask you to prove value.
      </p>

      <div className="steps">
        <div className="step">
          <div className="step-left"><div className="step-num">1</div><div className="step-line"></div></div>
          <div className="step-body">
            <h4>Your team keeps filing exactly as today</h4>
            <p>Every real GSTR-1, 3B, and payment still runs through your team, your process, your way. Your live process is completely untouched. Nothing of yours moves.</p>
          </div>
        </div>
        <div className="step">
          <div className="step-left"><div className="step-num">2</div><div className="step-line"></div></div>
          <div className="step-body">
            <h4>The same client data flows into Lekha AI in parallel</h4>
            <p>We ingest the same inputs — purchase register, GSTR-2B, outward supply data — and run our reconciliation, ITC categorisation, and 3B computation independently. Our output is a draft. It never reaches the portal.</p>
          </div>
        </div>
        <div className="step">
          <div className="step-left"><div className="step-num">3</div><div className="step-line"></div></div>
          <div className="step-body">
            <h4>Exceptions are flagged with source-traced reasoning</h4>
            <p>Not just "ITC mismatch found." But: "Vendor Sharma Traders — ₹1,24,500 not in GSTR-2B. Lekha suggests: hold credit + send vendor-chase message. Source: Purchase reg. row 412 ↔ 2B." The CA sees the exact source, the exact reasoning, and the suggested action.</p>
          </div>
        </div>
        <div className="step">
          <div className="step-left"><div className="step-num">4</div><div className="step-line"></div></div>
          <div className="step-body">
            <h4>You review, approve, override, or re-run — nothing posts without you</h4>
            <p>Every decision waits behind a visible human button. Approve. Override. Flag. Re-run. The action happens only on your click. Nothing files, pays, or sends until you press one.</p>
          </div>
        </div>
        <div className="step">
          <div className="step-left"><div className="step-num">5</div></div>
          <div className="step-body">
            <h4>End of each cycle: side-by-side comparison</h4>
            <p>Hours your team spent vs. hours Lekha took. Your ITC accuracy vs. Lekha's. Exceptions found in each. Cost per return. Measured against your own clients, your own numbers — not claimed savings from a demo.</p>
          </div>
        </div>
      </div>

      {/* ── PARALLEL RUN ── */}
      <div className="section-label">
        <span className="pill pill-solution">The Parallel Run</span>
        <hr />
      </div>

      <h2>Two Lanes. Same Data. Never Crossing.</h2>

      <p>
        The parallel run is not a pilot. A pilot switches a real client onto the AI to "see if it
        works" — and a mistake hits a live filing. The parallel run keeps both lanes completely
        separate. Your lane reaches the portal. Lekha's lane produces drafts and savings data. The
        lanes never cross.
      </p>

      <div className="two-lanes">
        <div className="lanes-header">
          <span>🔀 The Two-Lane Architecture — Identical Inputs, Independent Runs</span>
        </div>
        <div className="lanes-grid">
          <div className="lane-col">
            <span className="lane-label label-yours">YOUR LIVE LANE — untouched</span>
            <div className="lane-step"><span className="lane-box">Same client data</span><span className="lane-arrow">→</span><span className="lane-box">Your team</span></div>
            <div className="lane-step"><span className="lane-arrow">→</span><span className="lane-box">GST portal</span><span className="lane-arrow">→</span><span className="lane-box live">Filed — real</span></div>
          </div>
          <div className="lane-col">
            <span className="lane-label label-lekha">LEKHA PARALLEL LANE — shadow</span>
            <div className="lane-step"><span className="lane-box">Same client data</span><span className="lane-arrow">→</span><span className="lane-box shadow">Lekha AI</span></div>
            <div className="lane-step"><span className="lane-arrow">→</span><span className="lane-box">Drafts + savings</span><span className="lane-arrow">→</span><span className="lane-box notfiled">NOT filed</span></div>
          </div>
        </div>
        <div className="lanes-footer">The portal lock stays with you — only your lane reaches it. Lekha never files, pays, or sends during the parallel run.</div>
      </div>

      <h3>What Lekha Can and Cannot Do</h3>

      <div className="can-grid">
        <div className="can-card can-do">
          <h4>✓ What Lekha Can Do — Read &amp; Draft</h4>
          <ul>
            <li><span className="can-mark">·</span>Read the client data you share</li>
            <li><span className="can-mark">·</span>Read GSTR-2B / portal downloads you provide</li>
            <li><span className="can-mark">·</span>Reconcile, compute, and draft returns</li>
            <li><span className="can-mark">·</span>Measure hours, accuracy, and savings</li>
            <li><span className="can-mark">·</span>Flag exceptions with source-traced reasoning</li>
          </ul>
        </div>
        <div className="can-card cannot-do">
          <h4>✕ What Lekha Cannot Do — No Write Access</h4>
          <ul>
            <li><span className="can-mark" style={{ color: "#6B7280" }}>✕</span><span>File any return on the GST portal</span></li>
            <li><span className="can-mark" style={{ color: "#6B7280" }}>✕</span><span>Make any tax payment</span></li>
            <li><span className="can-mark" style={{ color: "#6B7280" }}>✕</span><span>Send anything to a client or the department</span></li>
            <li><span className="can-mark" style={{ color: "#6B7280" }}>✕</span><span>Hold standing portal credentials</span></li>
          </ul>
        </div>
      </div>

      <div className="callout callout-blue">
        <p>
          <strong>The control principle:</strong> The GST portal credentials stay with your firm —
          always. During the parallel run, Lekha is read-only by design.{" "}
          <strong>There is no path for it to file, pay, or send.</strong> When you move to go-live
          later, every irreversible action still waits behind a visible human confirmation. The lock
          never leaves your hand.
        </p>
      </div>

      <h3>The Human-in-the-Loop Review Screen</h3>
      <p>When Lekha AI reaches a decision — a draft complete or an exception identified — it stops and notifies you. Here is what that looks like:</p>

      <div className="review-screen">
        <div className="rs-bar">
          <div className="rs-dot" style={{ background: "#ef4444" }}></div>
          <div className="rs-dot" style={{ background: "#f59e0b" }}></div>
          <div className="rs-dot" style={{ background: "#10b981" }}></div>
          <span className="rs-title">Lekha AI — Review Queue</span>
        </div>
        <div className="rs-queue">
          <strong>Review Queue</strong>
          <span>Client: Acme Retail · March cycle · 3 items awaiting you</span>
        </div>
        <div className="rs-item">
          <span className="rs-flag">⚠ ITC Mismatch — Requires Your Decision</span>
          <p>Vendor "Sharma Traders" — ₹1,24,500 not in GSTR-2B. Lekha suggests: hold credit + send vendor-chase message.</p>
          <small>Source: Purchase reg. row 412 ↔ 2B · Nothing has been posted, filed, or sent.</small>
        </div>
        <div className="rs-actions">
          <button type="button" className="rs-btn btn-approve">Approve</button>
          <button type="button" className="rs-btn btn-override">Override</button>
          <button type="button" className="rs-btn btn-flag">Flag</button>
          <button type="button" className="rs-btn btn-rerun">Re-run</button>
          <span className="rs-note">On-screen buttons — nothing posts, pays or sends until you press one.</span>
        </div>
      </div>

      <h3>Every GST Flag Lekha Catches — Automatically</h3>

      <table className="flags-table">
        <thead>
          <tr>
            <th>Flag Type</th>
            <th>What It Means</th>
            <th>Why It Matters</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><span className="flag-dot"></span>ITC not in GSTR-2B</td>
            <td>Credit in books, vendor not uploaded</td>
            <td>Auto-reversal + interest from department</td>
          </tr>
          <tr>
            <td><span className="flag-dot"></span>Ineligible ITC claimed</td>
            <td>Section 17(5) or personal-use credit taken</td>
            <td>Penalty + reversal + scrutiny risk</td>
          </tr>
          <tr>
            <td><span className="flag-dot"></span>RCM liability missed</td>
            <td>Reverse charge not identified or computed</td>
            <td>Tax underpaid; interest from supply date</td>
          </tr>
          <tr>
            <td><span className="flag-dot"></span>Period mismatch</td>
            <td>Invoice in March, 2B reflects in April</td>
            <td>ITC in wrong period; creates tails each month</td>
          </tr>
          <tr>
            <td><span className="flag-dot"></span>IMS action deadline risk</td>
            <td>Vendor action window closing — no response yet</td>
            <td>Deemed accept or reject without CA decision</td>
          </tr>
          <tr>
            <td><span className="flag-dot"></span>GSTR-1 vs. 3B mismatch</td>
            <td>Output in 1 and 3B don't reconcile</td>
            <td>Scrutiny notice; reconciliation across returns</td>
          </tr>
          <tr>
            <td><span className="flag-dot"></span>Vendor-chase required</td>
            <td>Consistent non-upload by supplier</td>
            <td>Loses ITC if not chased and resolved in time</td>
          </tr>
        </tbody>
      </table>

      {/* ── IMPACT ── */}
      <div className="section-label">
        <span className="pill pill-impact">The Impact</span>
        <hr />
      </div>

      <h2>What the Parallel Run Measures — Cycle by Cycle</h2>

      <p>At the end of every cycle, savings are measured against your own baseline — not claimed numbers from a demo. Here is exactly what gets compared:</p>

      <table className="savings-table">
        <thead>
          <tr>
            <th>What We Measure</th>
            <th>Your Process Today</th>
            <th>Lekha Parallel Run</th>
            <th>What It Proves</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Hours per cycle</td>
            <td>Your current effort (baseline)</td>
            <td className="highlight-cell">↓ Large drop</td>
            <td className="proves-cell">Felt time-savings</td>
          </tr>
          <tr>
            <td>Automation rate</td>
            <td>Mostly manual</td>
            <td className="highlight-cell">~80% hands-off</td>
            <td className="proves-cell">The grind runs itself</td>
          </tr>
          <tr>
            <td>Accuracy vs. source</td>
            <td>Your current rate</td>
            <td className="highlight-cell">~90% AI alone · ~99% reviewed</td>
            <td className="proves-cell">Safe to rely on</td>
          </tr>
          <tr>
            <td>Deadline adherence</td>
            <td>Current misses</td>
            <td className="highlight-cell">Zero missed</td>
            <td className="proves-cell">No clock risk</td>
          </tr>
          <tr>
            <td>Cost per return-event</td>
            <td>Your current cost</td>
            <td className="highlight-cell">↓ Per event</td>
            <td className="proves-cell">Unit economics</td>
          </tr>
        </tbody>
      </table>

      <div className="callout callout-blue">
        <p>
          <strong>The baseline is yours, locked upfront.</strong> Every delta is measured against
          your own numbers on your own clients — so the value story is unarguable.{" "}
          <strong>You see exactly where the AI agrees, where it differs, and where it saves time</strong>{" "}
          — before a single live filing is ever involved.
        </p>
      </div>

      <h3>Three Months, Three Milestones</h3>

      <div className="timeline-3">
        <div className="tm-card">
          <div className="tm-header">
            <span className="month">Month 1</span>
            <h4>Set Up &amp; Lock the Baseline</h4>
          </div>
          <div className="tm-body">OTP access set up · ingest 2 toughest clients · lock today's hours, cost &amp; accuracy · shadow run begins.</div>
        </div>
        <div className="tm-card active">
          <div className="tm-header">
            <span className="month">Month 2</span>
            <h4>Run Both Lanes in Parallel</h4>
          </div>
          <div className="tm-body">Your live lane and our shadow lane run side by side · weekly comparison · tune on real exceptions.</div>
        </div>
        <div className="tm-card">
          <div className="tm-header">
            <span className="month">Month 3</span>
            <h4>Prove It — The Value Report</h4>
          </div>
          <div className="tm-body">Full-cycle side-by-side · the measured value report · go / no-go decision and pricing exercise.</div>
        </div>
      </div>

      <p style={{ fontSize: "0.82rem", color: "#6B7280", textAlign: "center", marginTop: "-0.5rem" }}>
        Throughout: OTP-gated, a 6-hour supervised daily window, full trace — from the very first day.
      </p>

      <h3>At Month 3 — You Decide, Having Risked Nothing</h3>

      <div className="decision-grid">
        <div className="dec-card dec-yes">
          <h4>✓ If It Clears the Bar</h4>
          <ul>
            <li><span className="dm">·</span>Move to a controlled, staged go-live</li>
            <li><span className="dm">·</span>Pricing set against measured value created</li>
            <li><span className="dm">·</span>Roll out across the wider client base</li>
            <li><span className="dm">·</span>Same controls carry forward</li>
          </ul>
        </div>
        <div className="dec-card dec-no">
          <h4>✕ If It Doesn't</h4>
          <ul>
            <li><span className="dm" style={{ color: "#6B7280" }}>·</span>You walk away — no lock-in</li>
            <li><span className="dm" style={{ color: "#6B7280" }}>·</span>Not one live filing was ever touched</li>
            <li><span className="dm" style={{ color: "#6B7280" }}>·</span>No penalty, interest or credit exposure</li>
            <li><span className="dm" style={{ color: "#6B7280" }}>·</span>You've lost nothing but a careful look</li>
          </ul>
        </div>
      </div>

      <h3>What Changes When GST Reconciliation Takes 30 Minutes</h3>

      <div className="stat-row">
        <div className="stat-card">
          <span className="num">~80%</span>
          <span className="desc">Of GST reconciliation work automated — without human intervention</span>
        </div>
        <div className="stat-card">
          <span className="num">~99%</span>
          <span className="desc">Accuracy after CA review — vs. your current manual baseline</span>
        </div>
        <div className="stat-card">
          <span className="num">Zero</span>
          <span className="desc">Missed deadlines — zero penalty and interest exposure during the parallel run</span>
        </div>
      </div>

      <p>
        <strong>For CA firms:</strong> A firm handling 20 clients spends 40–60 person-days on GST
        reconciliation every month. With Lekha AI, that drops to a fraction — freeing senior team
        members for advisory work, new client onboarding, and the judgment-based tasks that actually
        build firm value. The associate stops chasing formats. The SME stops doing line-by-line ITC
        matching. The partner reviews what genuinely needs their signature.
      </p>

      <p>
        <strong>For clients of CA firms:</strong> Faster GST cycles mean cleaner books, fewer notices,
        more accurate ITC positions, and advisors who have time to think rather than just file. The
        commodity layer of compliance gets compressed. The advisory relationship expands.
      </p>

      <div className="callout callout-green">
        <p>
          <strong>The bottom line:</strong> You never bet a filing on faith. You watch the savings
          add up — for three months — first.{" "}
          <strong>The reframe is simple: "trust us" becomes "watch us."</strong> The truth about
          savings becomes something you measure on your own clients — with the live filings never
          once at stake.
        </p>
      </div>

      {/* ── QUESTIONS ANSWERED ── */}
      <div className="section-label">
        <span className="pill pill-questions">Questions This Answers</span>
        <hr />
      </div>

      <h2>If You Found This Page Searching For…</h2>
      <p>This blog directly answers the following searches — on Google and in AI tools like ChatGPT, Perplexity, and Google AI Overviews:</p>

      <div className="q-grid">
        {[
          "How long does GST reconciliation take for a CA firm?",
          "How to automate GST reconciliation in India",
          "What is ITC reconciliation and why is it so hard?",
          "Why doesn't GSTR-2B match my purchase register?",
          "AI tools for GST filing and reconciliation India",
          "How to reduce GST compliance time for CA firms",
          "Can AI file GST returns automatically?",
          "GSTR-2B mismatch — how to fix and reconcile",
          "Best GST software for CA firms in India 2025",
          "How to automate ITC reconciliation for multiple clients",
          "GST automation software for chartered accountants",
          "How to handle IMS action deadline in GSTR-2B",
          "RCM liability reconciliation — how to automate",
          "Automated bookkeeping and GST filing for CA firms",
        ].map((q) => (
          <div className="q-item" key={q}>
            <span className="q-icon">Q</span>
            {q}
          </div>
        ))}
      </div>

      {/* ── SERIES ── */}
      <div className="series-box">
        <h4>📚 More from the ScaleupCFO Finance Operations Series</h4>
        <div className="series-links">
          <Link to="/blogs/why-book-closure-is-slow"><span className="sl-dot"></span>Why Month-End Book Closure Takes So Long — It's Not Your Team</Link>
          <Link to="/blogs/tds-reconciliation-10-minutes"><span className="sl-dot"></span>TDS Reconciliation in 10 Minutes: What That Actually Looks Like</Link>
          <Link to="/blogs/gap-between-finding-and-fixing-mismatch"><span className="sl-dot"></span>You Found the Mismatch. Now What?</Link>
          <Link to="/blogs/cfo-cash-position-real-time"><span className="sl-dot"></span>"What's Our Cash Position Right Now?" — Why Your CFO Doesn't Have a Real Answer</Link>
          <Link to="/blogs/sales-reconciliation-layers"><span className="sl-dot"></span>Why Sales Reconciliation Has So Many Layers — And How to Remove Them</Link>
          <Link to="/blogs/investor-mis-not-ready"><span className="sl-dot"></span>Investor Asked for MIS at 9pm. Your Books Weren't Ready.</Link>
          <Link to="/blogs/finance-ops-without-a-finance-team"><span className="sl-dot"></span>Your Startup Doesn't Need a Finance Team. It Needs a Finance Layer.</Link>
        </div>
      </div>

    </div>
  );
}
