import { Link } from "react-router-dom";

export default function GstReconciliation30Minutes() {
  return (
    <div className="blog-content">

      {/* ── PROBLEM ── */}
      <div className="section-label">
        <span className="pill pill-problem">The Problem</span>
        <hr />
      </div>

      <h2>The GST Filing Firefight That Repeats Every Single Month</h2>

      <p>
        Ask any CA partner what the last week of the month looks like and you will hear the same
        story. The associate opens Outlook to chase clients for purchase invoices. Someone downloads
        GSTR-2B and starts comparing it to the purchase register in Excel. ITC mismatches pile up.
        Vendors haven't uploaded. The 3B deadline is tomorrow. The partner signs off at 11pm.
      </p>

      <p>Next month, the exact same thing happens. Different client. Same firefight.</p>

      <div className="time-compare">
        <div className="tc-side tc-old">
          <span className="tc-label">Manual Process</span>
          <span className="tc-time">2-3 Days</span>
          <span className="tc-desc">GSTR-1, 2B matching, ITC reconciliation, 3B computation, all manual, all Excel</span>
        </div>
        <div className="tc-mid">
          <span>→</span>
          <small>vs</small>
        </div>
        <div className="tc-side tc-new">
          <span className="tc-label">With Lekha AI</span>
          <span className="tc-time">30 Min</span>
          <span className="tc-desc">~80% automated, exceptions flagged with reasoning, CA reviews and approves</span>
        </div>
      </div>

      <h3>Why GST Compliance Is So Painful Every Month</h3>
      <p>
        The problem is not that your team is slow. The problem is that the monthly GST cycle has ten
        steps, five different systems, and three points where human judgment is genuinely required,
        buried inside two days of mechanical work that should never have needed a human in the first
        place.
      </p>

      <ul className="pain-list">
        <li><span className="icon">📂</span>Sales and purchase data arrives in different formats from different clients (ERP exports, Tally data, Excel sheets, PDFs), and none of it is ready to reconcile without first being normalised.</li>
        <li><span className="icon">🔗</span>GSTR-2B and the purchase register are generated by entirely different systems and never match on the first pass. Someone always has to sit in between.</li>
        <li><span className="icon">⚖️</span>ITC reconciliation requires real judgment (eligible vs. ineligible, RCM entries, blocked credits, vendor-chase decisions), and it is also the most time-consuming step by far.</li>
        <li><span className="icon">⏰</span>The 11th and 20th don't move. So the team compresses everything into the last few days, and makes errors under deadline pressure that show up as notices three months later.</li>
        <li><span className="icon">💸</span>A wrong ITC claim is not just a software error. It is denied credit, interest liability, and a notice from the department, with real financial consequences for your client.</li>
      </ul>

      <div className="callout">
        <p><strong>The real cost:</strong> It is not just the 2-3 days per client. For a firm handling 20 clients, that is <strong>40-60 person-days of mechanical work every single month</strong>: work that could be automated, leaving almost no time for the advisory and judgment-based work that actually builds a firm's value.</p>
      </div>


      {/* ── THE WORKFLOW ── */}
      <div className="section-label">
        <span className="pill pill-workflow">The Monthly Workflow</span>
        <hr />
      </div>

      <h2>The 10-Step GST Cycle, and Where It Actually Breaks</h2>

      <p>
        Here is what the monthly GST compliance cycle looks like for one client: every step, every
        system, every friction point. The step marked in red is where most of the time goes and most
        of the risk lives.
      </p>

      <table className="workflow-table">
        <thead>
          <tr>
            <th>#</th>
            <th>Step</th>
            <th>System</th>
            <th>Friction</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td className="step-num-cell">1</td>
            <td>Chase &amp; collect client data: sales, purchase, invoices</td>
            <td>Outlook + WhatsApp + ERP/Tally</td>
            <td className="friction-cell">Formats vary; data always late</td>
          </tr>
          <tr>
            <td className="step-num-cell">2</td>
            <td>Normalise &amp; validate outward supplies</td>
            <td>Excel / GST software</td>
            <td className="friction-cell">HSN/rate cleanup; e-invoice/IRN matching</td>
          </tr>
          <tr>
            <td className="step-num-cell">3</td>
            <td>File GSTR-1 / IFF by 11th</td>
            <td>GST portal</td>
            <td className="friction-cell">Sequential dependency on prior data</td>
          </tr>
          <tr>
            <td className="step-num-cell">4</td>
            <td>Download GSTR-2B + take IMS actions</td>
            <td>GST portal</td>
            <td className="friction-cell">Vendor non-upload; deemed-accept risk</td>
          </tr>
          <tr className="hard-step">
            <td className="step-num-cell">5</td>
            <td><strong>ITC reconciliation</strong>: books vs. 2B + categorise (eligible / ineligible / RCM / s.17(5) blocked)</td>
            <td>Associate + SME for judgement</td>
            <td className="friction-cell">⚠️ The hardest, most judgement-laden, most time-burning step</td>
          </tr>
          <tr>
            <td className="step-num-cell">6</td>
            <td>Compute 3B liability: output ITC + RCM + interest</td>
            <td>Portal / Excel</td>
            <td className="friction-cell">Non-editable auto-pop; tie-outs</td>
          </tr>
          <tr>
            <td className="step-num-cell">7</td>
            <td>Client/partner sign-off on tax payable</td>
            <td>Outlook / in-person</td>
            <td className="friction-cell">Approval latency at deadline</td>
          </tr>
          <tr>
            <td className="step-num-cell">8</td>
            <td>Pay + file GSTR-3B by 20th</td>
            <td>GST portal</td>
            <td className="friction-cell">Deadline crunch across many clients at once</td>
          </tr>
          <tr>
            <td className="step-num-cell">9</td>
            <td>Handle routine notices / queries</td>
            <td>Portal / Outlook</td>
            <td className="friction-cell">Context-switching mid-cycle</td>
          </tr>
          <tr>
            <td className="step-num-cell">10</td>
            <td>File working papers, update tracker</td>
            <td>OneDrive / local Excel / human memory</td>
            <td className="friction-cell">Knowledge trapped in files &amp; heads</td>
          </tr>
        </tbody>
      </table>

      <div className="callout">
        <p><strong>Step 5 is the bottleneck:</strong> ITC reconciliation is the hardest, most judgment-laden, most time-burning step in the entire cycle. It is also <strong>the step where a wrong call has the most serious consequences</strong>: denied ITC, interest, notices. And it is currently done manually, under deadline pressure, for every client, every month.</p>
      </div>

      <h3>The Six GST Errors That Hide in Every Manual Reconciliation</h3>

      <div className="error-grid">
        <div className="error-card">
          <span className="etag">Error Type 1</span>
          <p><strong>ITC claimed not in GSTR-2B.</strong> Credit taken in books but vendor hasn't uploaded the invoice. Department auto-reverses it with interest. Client gets a notice.</p>
        </div>
        <div className="error-card">
          <span className="etag">Error Type 2</span>
          <p><strong>Ineligible ITC claimed.</strong> Credit on blocked items (Section 17(5)) or personal-use expenses incorrectly claimed as business. Penalty and reversal risk.</p>
        </div>
        <div className="error-card">
          <span className="etag">Error Type 3</span>
          <p><strong>RCM liability not accounted.</strong> Reverse Charge Mechanism applies but wasn't identified. Tax liability underpaid. Interest from the date of supply.</p>
        </div>
        <div className="error-card">
          <span className="etag">Error Type 4</span>
          <p><strong>Period mismatch on ITC.</strong> Invoice received in March, GSTR-2B reflects it in April. ITC taken in wrong period. Creates reconciliation tails that chase every future month.</p>
        </div>
        <div className="error-card">
          <span className="etag">Error Type 5</span>
          <p><strong>Vendor not chased, deemed accept.</strong> IMS action deadline missed. System auto-accepts or auto-rejects. Credit position changes without the CA knowing.</p>
        </div>
        <div className="error-card">
          <span className="etag">Error Type 6</span>
          <p><strong>GSTR-1 vs. 3B mismatch.</strong> Output liability in 3B doesn't match what was filed in GSTR-1. Creates scrutiny, notices, and reconciliation work across both returns.</p>
        </div>
      </div>

      <p>A manual process catches some of these. A well-built AI GST reconciliation engine catches all of them, with explanations, source references, and a human review step before anything is filed.</p>

      <div className="pull-quote">
        <p>A wrong GST filing is not a software bug.<br /><em>It is denied ITC, interest, a notice, and a client's trust.</em></p>
      </div>


      {/* ── SOLUTION ── */}
      <div className="section-label">
        <span className="pill pill-solution">The Solution</span>
        <hr />
      </div>

      <h2>How Lekha AI Handles GST Reconciliation, End to End</h2>

      <p>Most tools stop at detection: they show you a list of mismatches and hand it back. But a mismatch found is not a mismatch resolved. Lekha AI runs the full cycle (matching, categorising, chasing, and forcing every item to a terminal state before the period boundary) and only interrupts a human when a genuine judgement call is needed.</p>

      <div className="steps">
        <div className="step">
          <div className="step-left"><div className="step-num">1</div><div className="step-line"></div></div>
          <div className="step-body">
            <h4>Ingest the inputs: books and the portal, normalised</h4>
            <p>The purchase register from Tally or Zoho, GSTR-2B from the GSTN portal, and the live IMS view flow in. Lekha normalises the formats (HSN, rates, GSTIN, invoice numbers, IRNs) so everything is on a common footing before a single line is matched. No manual cleanup.</p>
          </div>
        </div>
        <div className="step">
          <div className="step-left"><div className="step-num">2</div><div className="step-line"></div></div>
          <div className="step-body">
            <h4>The rule engine matches books against 2B, no VLOOKUP</h4>
            <p>Where a team drags VLOOKUPs across two sheets and eyeballs the gaps, Lekha's rule engine matches on GSTIN + invoice number + date + taxable value + tax heads, applies your firm's tolerance policy, and settles the clean matches automatically. What's left is only the genuine exceptions: the non-reconciled items that actually need a decision.</p>
          </div>
        </div>
        <div className="step">
          <div className="step-left"><div className="step-num">3</div><div className="step-line"></div></div>
          <div className="step-body">
            <h4>Agents close the non-reconciled items in the background</h4>
            <p>For each exception, an agent works the disposition on its own: separating a timing gap from a genuine default, drafting the vendor-chase message, marking a genuinely-unbooked invoice 'Pending' in IMS instead of wrongly rejecting it, or holding an ITC roll-forward to the correct period. It runs quietly; you are not watching a queue tick down.</p>
          </div>
        </div>
        <div className="step">
          <div className="step-left"><div className="step-num">4</div><div className="step-line"></div></div>
          <div className="step-body">
            <h4>Only judgement calls surface for a human</h4>
            <p>Safe, reversible steps are handled automatically. What reaches you is the short list that genuinely needs a person: a credit note whose reversal affects availed ITC, a suspended-supplier reversal, a place-of-supply call. Each arrives with the source rows, the reasoning, the citation, and a suggested action, ready to approve, override, or send.</p>
          </div>
        </div>
        <div className="step">
          <div className="step-left"><div className="step-num">5</div><div className="step-line"></div></div>
          <div className="step-body">
            <h4>Nothing irreversible fires without your confirmation</h4>
            <p>Filing, paying, sending a vendor message, committing an IMS accept/reject: every action that cannot be undone waits behind a visible human button. And every step Lekha takes, automatic or approved, is written to an immutable log: what happened, when, why, and against which source.</p>
          </div>
        </div>
      </div>


      {/* ── CLOSING THE LOOP ── */}
      <div className="section-label">
        <span className="pill pill-workflow">Closing The Loop</span>
        <hr />
      </div>

      <h2>Catching the Mismatch Is the Easy 10%. Closing It Is the Other 90%.</h2>

      <p>Finding a gap between your books and 2B is trivial. The work is <em>disposition</em>: driving every non-reconciled item to a terminal state before the period closes. It is never one problem but a set of distinct <strong>use cases</strong>, each with its own correct handling. Lekha's accelerator sorts each item into one of five buckets (A to E) and routes it down the lane that closes it. Here is the full map.</p>

      <div className="tree">
        <div className="tree-top">
          <div className="tree-source">
            <span className="ts-label">Reconciliation engine</span>
            <span className="ts-sub">match key: GSTIN + inv no + date + taxable value + tax heads, within tolerance</span>
          </div>
          <div className="tree-split">
            <span className="tree-pill reconciled">Reconciled → accept in IMS → lock ITC → GSTR-3B Table 4</span>
            <span className="tree-pill nonrecon">Non-reconciled → sort into buckets A to E ↓</span>
          </div>
        </div>

        <div className="tree-buckets">
          <div className="tbucket tb-chase">
            <span className="tb-tag">A · Supplier-side gap</span>
            <span className="tb-title">In books, not in 2B</span>
            <p className="tb-body">Supplier GSTR-1 unfiled (timing vs default), wrong GSTIN. Roll timing forward &amp; age; amend via Table 9A.</p>
            <span className="tb-route route-chase">→ Chase Vendor</span>
          </div>
          <div className="tbucket tb-internal">
            <span className="tb-tag">B · Our-side / ops gap</span>
            <span className="tb-title">In 2B, not in books</span>
            <p className="tb-body">Booking lag → 'Pending'. Unbooked past ~3 periods → escalate on the internal governance cap.</p>
            <span className="tb-route route-internal">→ Internal Chase</span>
          </div>
          <div className="tbucket tb-chase">
            <span className="tb-tag">C · Value / document</span>
            <span className="tb-title">Mismatch or duplicate</span>
            <p className="tb-body">Beyond tolerance → request DN/CN. Duplicate → de-dup on IRN. Cancelled IRN → verify IRP, don't claim.</p>
            <span className="tb-route route-chase">→ Chase Vendor</span>
          </div>
          <div className="tbucket tb-force">
            <span className="tb-tag">D · IMS / credit-note</span>
            <span className="tb-title">Mechanics [not ISD]</span>
            <p className="tb-body">'No Action' &amp; pending CN → deemed accepted. Force a decision; defer if pre-filing; re-furnish via GSTR-1A if wrongly rejected.</p>
            <span className="tb-route route-force">→ Force IMS Decision</span>
          </div>
          <div className="tbucket tb-force">
            <span className="tb-tag">E · Import &amp; special-status</span>
            <span className="tb-title">Timing, not discrepancy</span>
            <p className="tb-body">BoE not synced → verify ICEGATE. Vanished 2B → check Rule 37A. QRMP → track off the quarterly 2B.</p>
            <span className="tb-route route-force">→ Verify / Force IMS</span>
          </div>
        </div>

        <div className="tree-lanes">
          <span className="tl-chip lane-chase"><strong>Chase Vendor</strong> · revised GSTR-1 / Table 9A / re-furnish GSTR-1A · log every chase immutably (burden of proof)</span>
          <span className="tl-chip lane-internal"><strong>Internal Chase</strong> · procurement / AP to book · verify ICEGATE for imports</span>
          <span className="tl-chip lane-force"><strong>Force IMS Decision</strong> · accept / reject / declared reversal before the period boundary</span>
        </div>

        <div className="tree-terminal">
          <span className="tt-label">Re-run recon next period → lock final 2B → ITC into GSTR-3B Table 4</span>
          <span className="tt-sub">every item ends: claimed · rolled forward · reversed · written off, or aged into the next period, never dropped</span>
        </div>
      </div>

      <p>The single most expensive mistake is treating a <strong>timing gap</strong> (a late GSTR-1 that simply lands in next month's 2B) as a genuine default and reversing the ITC, when the right move is to roll it forward and age it. Get the bucket wrong and the credit reappears next month to be untangled, or an IMS deadline slips and the ITC moves silently.</p>

      <div className="callout callout-blue">
        <p><strong>Why the discipline is not optional now:</strong> since October 2025, IMS deemed-acceptance is the legal basis for ITC (Section 38 substituted, Rule 67B), and 3B liability has been hard-locked since July 2025 with corrections flowing only through GSTR-1A. Rule 88D / DRC-01C also triggers an automatic intimation whenever 3B ITC exceeds 2B by more than ₹1 lakh or 20%, with a 7-day response window. A silently deemed-accepted record is no longer housekeeping; it is an intimation waiting to happen.</p>
      </div>

      <h3>The control principle: autonomy you can see and stop</h3>
      <p>Lekha's agents are autonomous on the safe, reversible steps: normalising data, matching within tolerance, marking 'Pending', drafting a chase, deferring an IMS action until the supplier files. But three rules hold at every level of autonomy:</p>

      <div className="can-grid">
        <div className="can-card can-do">
          <h4>✓ What Runs Automatically: Safe &amp; Reversible</h4>
          <ul>
            <li><span className="can-mark">·</span>Normalise and match books against 2B</li>
            <li><span className="can-mark">·</span>Settle clean matches within tolerance</li>
            <li><span className="can-mark">·</span>Mark genuine booking-lag items 'Pending'</li>
            <li><span className="can-mark">·</span>Draft vendor-chase messages &amp; log them</li>
            <li><span className="can-mark">·</span>Roll timing-gap ITC to the correct period</li>
            <li><span className="can-mark">·</span>Defer an IMS action until the supplier files</li>
          </ul>
        </div>
        <div className="can-card cannot-do">
          <h4>✕ What Never Fires Without You</h4>
          <ul>
            <li><span className="can-mark" style={{ color: "#6B7280" }}>✕</span><span>File any return on the GST portal</span></li>
            <li><span className="can-mark" style={{ color: "#6B7280" }}>✕</span><span>Make any tax payment</span></li>
            <li><span className="can-mark" style={{ color: "#6B7280" }}>✕</span><span>Send a vendor message before you approve it</span></li>
            <li><span className="can-mark" style={{ color: "#6B7280" }}>✕</span><span>Commit an IMS accept / reject / reversal</span></li>
          </ul>
        </div>
      </div>

      <div className="callout callout-forest">
        <p><strong>The three rules, always:</strong> (1) Lekha explains what it is doing and why, at every step. (2) You can pause, override, or stop any action at any moment. (3) No irreversible action (file, pay, send, commit an IMS decision) executes without a visible confirmation. The GST portal credentials stay with your firm. The lock never leaves your hand.</p>
      </div>

      <h3>The Human-in-the-Loop Review Screen</h3>
      <p>The agents run in the background. When one hits something that genuinely needs a person, it stops and surfaces it, with everything you need to decide in one place:</p>

      <div className="review-screen">
        <div className="rs-bar">
          <div className="rs-dot" style={{ background: "#ef4444" }}></div>
          <div className="rs-dot" style={{ background: "#f59e0b" }}></div>
          <div className="rs-dot" style={{ background: "#10b981" }}></div>
          <span className="rs-title">Lekha AI · Review Queue</span>
        </div>
        <div className="rs-queue">
          <strong>Review Queue</strong>
          <span>Client: Acme Retail · March cycle · 214 items reconciled automatically · 3 need you</span>
        </div>
        <div className="rs-item">
          <span className="rs-flag">⚠ Credit Note · Judgement Call Required</span>
          <p>Vendor "Sharma Traders" issued CN ₹42,000. Rejecting it would raise their liability. Lekha reads it as genuine and suggests: accept &amp; reverse only the ₹31,500 ITC actually availed.</p>
          <small>IMS mechanics · Oct-2025 declared-reversal feature · Source: 2B CN ↔ purchase reg. row 412 · Nothing has been posted or committed.</small>
        </div>
        <div className="rs-actions">
          <button className="rs-btn btn-approve">Approve suggestion</button>
          <button className="rs-btn btn-override">Override</button>
          <button className="rs-btn btn-flag">Route to partner</button>
          <button className="rs-btn btn-rerun">Re-run</button>
          <span className="rs-note">On-screen buttons; no IMS decision commits until you press one.</span>
        </div>
      </div>

      <p style={{ fontSize: "0.9rem", color: "#6B7280" }}>Behind that one card, the agents already settled 214 clean matches, marked six booking-lag invoices 'Pending', drafted two vendor chases, and rolled one late-GSTR-1 credit to next month, none of which needed your attention. You see the 3 that do.</p>


      {/* ── IMPACT ── */}
      <div className="section-label">
        <span className="pill pill-impact">The Impact</span>
        <hr />
      </div>

      <h2>What Changes When the Closing Loop Runs Itself</h2>

      <p>The time doesn't disappear because matching got faster. It disappears because the disposition work (the chasing, the 'Pending' discipline, the forced IMS decisions, the ageing) stops being manual. Here is where the effort actually goes in a Lekha cycle:</p>

      <table className="savings-table">
        <thead>
          <tr>
            <th>The Work</th>
            <th>Manual Today</th>
            <th>With Lekha AI</th>
            <th>What Frees Up</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Matching books vs. 2B</td>
            <td>VLOOKUP across two sheets, by hand</td>
            <td className="highlight-cell">Rule engine, automatic</td>
            <td className="proves-cell">The whole first pass</td>
          </tr>
          <tr>
            <td>Non-reconciled disposition</td>
            <td>Manual, per item, per vendor</td>
            <td className="highlight-cell">Agents work it in the background</td>
            <td className="proves-cell">The 90% that ate the days</td>
          </tr>
          <tr>
            <td>Vendor chasing</td>
            <td>Ad-hoc WhatsApp / email, untracked</td>
            <td className="highlight-cell">Drafted, sent, logged for proof</td>
            <td className="proves-cell">Follow-up + evidence trail</td>
          </tr>
          <tr>
            <td>IMS decisions</td>
            <td>Easy to miss → deemed accept</td>
            <td className="highlight-cell">Forced before the boundary</td>
            <td className="proves-cell">Silent ITC leakage</td>
          </tr>
          <tr>
            <td>What reaches a human</td>
            <td>Everything</td>
            <td className="highlight-cell">Only genuine judgement calls</td>
            <td className="proves-cell">Attention for what matters</td>
          </tr>
        </tbody>
      </table>

      <div className="callout callout-forest">
        <p><strong>The shift:</strong> your team stops doing the reconciliation and starts <strong>reviewing the exceptions that genuinely need a person</strong>. The associate stops dragging VLOOKUPs. The SME stops working every mismatch by hand. The partner reviews only what carries real judgement: a credit-note reversal, a blocked-credit call, a suspended-supplier decision.</p>
      </div>

      <h3>What Changes When GST Reconciliation Takes 30 Minutes</h3>

      <div className="stat-row">
        <div className="stat-card">
          <span className="num">~80%</span>
          <span className="desc">Of GST reconciliation work automated, without human intervention</span>
        </div>
        <div className="stat-card">
          <span className="num">~99%</span>
          <span className="desc">Accuracy after CA review, vs. your current manual baseline</span>
        </div>
        <div className="stat-card">
          <span className="num">Zero</span>
          <span className="desc">Non-reconciled items left open: every one driven to a terminal state or aged forward</span>
        </div>
      </div>

      <p><strong>For CA firms:</strong> A firm handling 20 clients spends 40-60 person-days on GST reconciliation every month, and most of that is the disposition work, not the matching. With Lekha AI, that drops to a fraction, freeing senior team members for advisory work, new client onboarding, and the judgment-based tasks that actually build firm value. The associate stops chasing formats. The SME stops doing line-by-line ITC matching. The partner reviews only what genuinely needs their signature.</p>

      <p><strong>For clients of CA firms:</strong> Cleaner books, fewer notices, more accurate ITC positions, and a documented chase trail if the department ever asks. Because every non-reconciled item is closed (not just flagged) the reconciliation tail that normally drags into future months never forms. The commodity layer of compliance gets compressed. The advisory relationship expands.</p>

      <div className="callout callout-green">
        <p><strong>The bottom line:</strong> Finding the mismatch was never the hard part. Closing it (the chasing, the IMS discipline, the ageing, the evidence) is what took the days and caused the notices. <strong>Lekha AI runs that closing loop end to end, in the background, and only asks you to decide the calls that genuinely need a human.</strong> Everything it does, you can see, pause, or override, and nothing irreversible fires without your confirmation.</p>
      </div>


      {/* ── QUESTIONS ── */}
      <div className="section-label">
        <span className="pill pill-questions">Questions This Answers</span>
        <hr />
      </div>

      <h2>If You Found This Page Searching For…</h2>
      <p>This blog directly answers the following searches, on Google and in AI tools like ChatGPT, Perplexity, and Google AI Overviews:</p>

      <div className="q-grid">
        <div className="q-item"><span className="q-icon">Q</span>How long does GST reconciliation take for a CA firm?</div>
        <div className="q-item"><span className="q-icon">Q</span>How to automate GST reconciliation in India</div>
        <div className="q-item"><span className="q-icon">Q</span>What is ITC reconciliation and why is it so hard?</div>
        <div className="q-item"><span className="q-icon">Q</span>Why doesn't GSTR-2B match my purchase register?</div>
        <div className="q-item"><span className="q-icon">Q</span>AI tools for GST filing and reconciliation India</div>
        <div className="q-item"><span className="q-icon">Q</span>How to reduce GST compliance time for CA firms</div>
        <div className="q-item"><span className="q-icon">Q</span>Can AI file GST returns automatically?</div>
        <div className="q-item"><span className="q-icon">Q</span>GSTR-2B mismatch: how to fix and reconcile</div>
        <div className="q-item"><span className="q-icon">Q</span>Best GST software for CA firms in India 2025</div>
        <div className="q-item"><span className="q-icon">Q</span>How to automate ITC reconciliation for multiple clients</div>
        <div className="q-item"><span className="q-icon">Q</span>GST automation software for chartered accountants</div>
        <div className="q-item"><span className="q-icon">Q</span>How to handle IMS action deadline in GSTR-2B</div>
        <div className="q-item"><span className="q-icon">Q</span>RCM liability reconciliation: how to automate</div>
        <div className="q-item"><span className="q-icon">Q</span>Automated bookkeeping and GST filing for CA firms</div>
        <div className="q-item"><span className="q-icon">Q</span>Late GSTR-1: should I reverse ITC or roll it forward?</div>
        <div className="q-item"><span className="q-icon">Q</span>IMS 'Pending' vs reject in GSTR-2B: when to use which</div>
        <div className="q-item"><span className="q-icon">Q</span>How to automate vendor follow-up for missing GST invoices</div>
      </div>


      {/* ── SERIES ── */}
      <div className="series-box">
        <h4>📚 More from the Lekha AI Finance Operations Series</h4>
        <div className="series-links">
          <Link to="/blogs/why-book-closure-is-slow"><span className="sl-dot"></span>Why Does Month-End Book Closure Take So Long? It's Not Your Team.</Link>
          <Link to="/blogs/tds-reconciliation-10-minutes"><span className="sl-dot"></span>TDS Reconciliation Takes Your Team 3 Days. It Takes AI 10 Minutes.</Link>
          <Link to="/blogs/gap-between-finding-and-fixing-mismatch"><span className="sl-dot"></span>You Found the Mismatch. Now What?</Link>
          <Link to="/blogs/sales-reconciliation-layers"><span className="sl-dot"></span>Why Sales Reconciliation Has So Many Layers, And How to Remove Them.</Link>
          <Link to="/blogs/investor-mis-not-ready"><span className="sl-dot"></span>Investor Asked for MIS at 9pm. Your Books Weren't Ready. Here's Why.</Link>
        </div>
      </div>

    </div>
  );
}
